In [1]:
import numpy as np
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df= pd.read_csv("cleaned_data.csv")

In [3]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [4]:
X = df[['gender', 'Partner', 'Dependents', 
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',]]
X1 = df[['SeniorCitizen','tenure','MonthlyCharges', 'TotalCharges']]
y = df['Churn']

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [6]:
for i in X.columns:
    X[i] = le.fit_transform(X[i])

In [7]:
X

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,0,1,0,0,1,0,0,2,0,0,0,0,0,1,2
1,1,0,0,1,0,0,2,0,2,0,0,0,1,0,3
2,1,0,0,1,0,0,2,2,0,0,0,0,0,1,3
3,1,0,0,0,1,0,2,0,2,2,0,0,1,0,0
4,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7005,1,1,1,1,2,0,2,0,2,2,2,2,1,1,3
7006,0,1,1,1,2,1,0,2,2,0,2,2,1,1,1
7007,0,1,1,0,1,0,2,0,0,0,0,0,0,1,2
7008,1,1,0,1,2,1,0,0,0,0,0,0,0,1,3
7009,1,0,0,1,0,1,2,0,2,2,2,2,2,1,0

In [8]:
 X = pd.concat([X, X1], axis=1)

In [9]:
X

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,SeniorCitizen,tenure,MonthlyCharges,TotalCharges
0,0,1,0,0,1,0,0,2,0,0,0,0,0,1,2,0,1,29.85,29.85
1,1,0,0,1,0,0,2,0,2,0,0,0,1,0,3,0,34,56.95,1889.50
2,1,0,0,1,0,0,2,2,0,0,0,0,0,1,3,0,2,53.85,108.15
3,1,0,0,0,1,0,2,0,2,2,0,0,1,0,0,0,45,42.30,1840.75
4,0,0,0,1,0,1,0,0,0,0,0,0,0,1,2,0,2,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7005,1,1,1,1,2,0,2,0,2,2,2,2,1,1,3,0,24,84.80,1990.50
7006,0,1,1,1,2,1,0,2,2,0,2,2,1,1,1,0,72,103.20,7362.90
7007,0,1,1,0,1,0,2,0,0,0,0,0,0,1,2,0,11,29.60,346.45
7008,1,1,0,1,2,1,0,0,0,0,0,0,0,1,3,1,4,74.40,306.60
7009,1,0,0,1,0,1,2,0,2,2,2,2,2,1,0,0,66,105.65,6844.50

In [14]:
from sklearn.model_selection import train_test_split 
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
scores = []

for i in range(0,101):
    X_train, X_test, y_train, y_test = train_test_split (X,y,test_size=0.1, random_state=i, stratify=y)
    smote=SMOTE(random_state=42)
    X_resampled,y_resampled=smote.fit_resample(X_train,y_train)

    

# Create model
    model = RandomForestClassifier(
    n_estimators=100,
    criterion='gini',
    random_state=42
    )
    model.fit(X_resampled, y_resampled)
    y_pred = model.predict(X_test)
    score = accuracy_score(y_test, y_pred)
    scores.append(score)

In [15]:
scores

[0.7589158345221113,
 0.7574893009985735,
 0.7746077032810271,
 0.7746077032810271,
 0.7902995720399429,
 0.7746077032810271,
 0.7617689015691869,
 0.8045649072753209,
 0.7945791726105563,
 0.7717546362339515,
 0.7831669044222539,
 0.7774607703281027,
 0.7489300998573466,
 0.7788873038516405,
 0.7703281027104137,
 0.7503566333808844,
 0.7589158345221113,
 0.7902995720399429,
 0.7774607703281027,
 0.7532097004279601,
 0.7703281027104137,
 0.7617689015691869,
 0.797432239657632,
 0.7717546362339515,
 0.7717546362339515,
 0.7617689015691869,
 0.7517831669044223,
 0.7703281027104137,
 0.7746077032810271,
 0.7574893009985735,
 0.7703281027104137,
 0.7831669044222539,
 0.7817403708987162,
 0.776034236804565,
 0.8017118402282454,
 0.7845934379457917,
 0.7631954350927247,
 0.8002853067047075,
 0.7860199714693296,
 0.7475035663338089,
 0.7746077032810271,
 0.7746077032810271,
 0.8017118402282454,
 0.7646219686162625,
 0.7917261055634808,
 0.7574893009985735,
 0.760342368045649,
 0.7546362339514978,
 0.760342368045649,
 0.7803138373751783,
 0.7674750356633381,
 0.7717546362339515,
 0.7945791726105563,
 0.7888730385164051,
 0.7774607703281027,
 0.8017118402282454,
 0.7703281027104137,
 0.8102710413694721,
 0.7774607703281027,
 0.7617689015691869,
 0.7774607703281027,
 0.7560627674750356,
 0.7660485021398002,
 0.7831669044222539,
 0.7845934379457917,
 0.7746077032810271,
 0.7489300998573466,
 0.7560627674750356,
 0.7574893009985735,
 0.7717546362339515,
 0.7902995720399429,
 0.7589158345221113,
 0.7717546362339515,
 0.7803138373751783,
 0.7860199714693296,
 0.7589158345221113,
 0.7617689015691869,
 0.776034236804565,
 0.7703281027104137,
 0.7574893009985735,
 0.760342368045649,
 0.7489300998573466,
 0.7845934379457917,
 0.7788873038516405,
 0.7674750356633381,
 0.7888730385164051,
 0.7860199714693296,
 0.7574893009985735,
 0.8017118402282454,
 0.7731811697574893,
 0.7817403708987162,
 0.7888730385164051,
 0.7332382310984308,
 0.7560627674750356,
 0.7888730385164051,
 0.8074179743223966,
 0.7703281027104137,
 0.7774607703281027,
 0.776034236804565,
 0.7774607703281027,
 0.7788873038516405]

In [16]:
index=np.argmax(scores)

In [17]:
index

np.int64(57)

In [18]:
scores[index]

0.8102710413694721

In [19]:
import pickle
pickle.dump(model,open("model.pkl","wb"))

In [21]:
df['PaymentMethod'].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [22]:
df['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)